[profile.default]
src = 'contracts'
bytecode_hash = 'none'
solc_version = "0.8.10"
libs = ["lib"]
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
mode = "${MODE_MAINNET_RPC_URL}"

mode_archive = "${MODE_MAINNET_ARCHIVE_RPC_URL}"

# See more config options https://github.com/gakonst/foundry/tree/master/config
